"$schema" = "https://starship.rs/config-schema.json"

format = """
[â•­](fg:current_line)\
$os\
$status\
$directory\
$git_branch\
$git_status\
$docker_context\
$fill\
$package\
$golang\
$nodejs\
$bun\
$deno\
$python\
$java\
$zig\
$rust\
$c\
$cmd_duration\
$time\
$username\
$line_break\
$character\
"""

palette = "gruvbox_dark"
add_newline = true

[palettes.gruvbox_dark]
foreground = "#ebdbb2"
background = "#282828"
current_line = "#3c3836"
primary = "#83a598"
box = "#504945"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
orange = "#fe8019"
pink = "#d3869b"
purple = "#b16286"
red = "#fb4934"
yellow = "#fabd2f"
status = "#83a598"

[os]
format = '(fg:current_line)[î‚¶](fg:red)[$symbol](fg:foreground bg:red)[î‚´](fg:red)'
disabled = false

[status]
format = "[â”€](fg:current_line)[î‚¶](fg:status)[î½¶](fg:foreground bg:status)[î‚´](fg:status bg:box)[ $status](fg:foreground bg:box)[î‚´](fg:box)"
pipestatus = true
pipestatus_separator = "-"
pipestatus_segment_format = "$status"
pipestatus_format = "[â”€](fg:current_line)[î‚¶](fg:status)[î½¶](fg:foreground bg:status)[î‚´](fg:status bg:box)[ $pipestatus](fg:foreground bg:box)[î‚´](fg:box)"
disabled = false

[directory]
format = '[â”€](fg:current_line)[î‚¶](fg:pink)[ó°·](fg:foreground bg:pink)[î‚´](fg:pink bg:box)[ $read_only$truncation_symbol$path](fg:foreground bg:box)[î‚´](fg:box)'
home_symbol = "î­† ~/"
truncation_symbol = "î¯Ÿ "
truncation_length = 2
read_only = "ó±§µ "
read_only_style = ""

[git_branch]
format = '[â”€](fg:current_line)[î‚¶](fg:green)[$symbol](fg:foreground bg:green)[î‚´](fg:green bg:box)[ $branch](fg:foreground bg:box)'
symbol = "ï—"

[git_status]
format = '[$all_status](fg:green bg:box)[î‚´](fg:box)'
conflicted = " ="
up_to_date = ""
untracked = " ?${count}"
stashed = " $"
modified = " !${count}"
staged = " +"
renamed = " Â»"
deleted = " âœ˜"
ahead = " â‡¡${count}"
diverged = " â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = " â‡£${count}"

[docker_context]
format = '[â”€](fg:current_line)[î‚¶](fg:blue)[ïŒˆ](fg:foreground bg:blue)[î‚´](fg:blue bg:box)[ $context](fg:foreground bg:box)[î‚´](fg:box)'

[package]
format = '[â”€](fg:current_line)[î‚¶](fg:orange)[ğŸ“¦](fg:foreground bg:orange)[î‚´](fg:orange bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'

[nodejs]
format = '[â”€](fg:current_line)[î‚¶](fg:green)[$symbol](fg:foreground bg:green)[î‚´](fg:green bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'
symbol = "ó°™ Node.js"

[bun]
format = '[â”€](fg:current_line)[î‚¶](fg:green)[$symbol](fg:foreground bg:green)[î‚´](fg:green bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'
symbol = "î¯ Bun"

[deno]
format = '[â”€](fg:current_line)[î‚¶](fg:purple)[$symbol](fg:foreground bg:purple)[î‚´](fg:purple bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'
symbol = "ğŸ¦• Deno"

[zig]
format = '[â”€](fg:current_line)[î‚¶](fg:blue)[$symbol](fg:foreground bg:blue)[î‚´](fg:blue bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'
symbol = "âš¡ï¸ Zig"

[rust]
format = '[â”€](fg:current_line)[î‚¶](fg:yellow)[$symbol](fg:foreground bg:yellow)[î‚´](fg:yellow bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'
symbol = "î¨ Rust"

[python]
format = '[â”€](fg:current_line)[î‚¶](fg:green)[$symbol](fg:foreground bg:green)[î‚´](fg:green bg:box)[ $version$virtualenv](fg:foreground bg:box)[î‚´](fg:box)'
symbol = "îœ¼ python"

[java]
format = '[â”€](fg:current_line)[î‚¶](fg:red)[$symbol](fg:foreground bg:red)[î‚´](fg:red bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'
symbol = "îœ¸ Java"

[golang]
format = '[â”€](fg:current_line)[î‚¶](fg:red)[$symbol](fg:foreground bg:red)[î‚´](fg:red bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'
symbol = "ó°‘® Go"

[c]
format = '[â”€](fg:current_line)[î‚¶](fg:blue)[$symbol](fg:foreground bg:blue)[î‚´](fg:blue bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'
symbol = "î˜ C"

[fill]
symbol = "â”€"
style = "fg:current_line"

[cmd_duration]
min_time = 1000
format = '[â”€](fg:current_line)[î‚¶](fg:orange)[ïƒ§](fg:background bg:orange)[î‚´](fg:orange bg:box)[ $duration](fg:foreground bg:box)[î‚´](fg:box)'

[time]
format = '[â”€](fg:current_line)[î‚¶](fg:purple)[ó°¦–](fg:background bg:purple)[î‚´](fg:purple bg:box)[ $time](fg:foreground bg:box)[î‚´](fg:box)'
time_format = "%H:%M"
disabled = false

[username]
format = '[â”€](fg:current_line)[î‚¶](fg:yellow)[ï•](fg:background bg:yellow)[î‚´](fg:yellow bg:box)[ $user](fg:foreground bg:box)[î‚´](fg:box)'
show_always = false

[character]
format = """
[â•°â”€$symbol](fg:current_line) """
success_symbol = '[ïƒš](fg:green bold)'
error_symbol = '[Ã—](fg:red bold)'

[profiles]
transient = "$character"
